=== acumos/on-boarding/onboarding-common/src/main/resources/model-schema-0.4.0.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "self": {
    "name": "acumos.schema.model",
    "version": "0.4.0"
  },
  "properties": {
    "schema": {
      "type": "string",
      "pattern": "^acumos.schema.model:\\d+\\.\\d+\\.\\d+$",
      "description": "Identifies the specific model schema used in the json instance, e.g. 'acumos.schema.model:0.4.0'."
    },
    "name": {
      "type": "string",
      "description": "The name of the model being on-boarded to Acumos, e.g. 'my-model'."
    },
    "runtime": {
      "$ref": "#/definitions/Runtime",
      "description": "Describes the runtime and dependencies required by the model to operate."
    },
    "methods": {
      "type": "object",
      "description": "The methods that an on-boarded model provides. Can be any number of uniquely named Function or VoidFunction objects.",
      "additionalProperties": {
        "anyOf": [
          {
            "$ref": "#/definitions/Function"
          },
          {
            "$ref": "#/definitions/VoidFunction"
          }
        ]
      }
    }
  },
  "required": [
    "runtime",
    "methods",
    "schema",
    "name"
  ],
  "definitions": {
    "Runtime": {
      "type": "object",
      "properties": {
        "name": {
          "enum": [
            "python",
            "r",
            "javaargus",
            "h2o",
            "javageneric",
            "javaspark"
          ]
        },
        "version": {
          "type": "string"
        },
        "encoding": {
          "enum": [
            "protobuf"
          ]
        },
        "dependencies": {
          "oneOf": [
            {
              "$ref": "#/definitions/PythonDependencies"
            },
            {
              "$ref": "#/definitions/RDependencies"
            },
            {
              "$ref": "#/definitions/H2ODependencies"
            }
          ]
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "RDependencies": {
      "type": "object",
      "properties": {
        "packages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PackRequirements"
          }
        }
      },
      "required": [
        "packages"
      ]
    },
    "RDependenciesPackages": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "repository": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "H2ODependencies": {
      "type": "object",
      "properties": {
        "java": {
          "$ref": "#/definitions/JavaRequirements"
        }
      },
      "required": [
        "java"
      ]
    },
    "JavaRequirements": {
      "type": "object",
      "properties": {
        "indexes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "requirements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/H2ORequirement"
          }
        }
      },
      "required": [
        "indexes",
        "requirements"
      ]
    },
    "H2ORequirement": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "PackRequirements": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "PythonDependencies": {
      "type": "object",
      "properties": {
        "conda": {
          "$ref": "#/definitions/CondaRequirements"
        },
        "pip": {
          "$ref": "#/definitions/PipRequirements"
        }
      },
      "required": [
        "pip",
        "conda"
      ]
    },
    "PipRequirements": {
      "type": "object",
      "properties": {
        "indexes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "requirements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PythonRequirement"
          }
        }
      },
      "required": [
        "indexes",
        "requirements"
      ]
    },
    "CondaRequirements": {
      "type": "object",
      "properties": {
        "channels": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "requirements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PythonRequirement"
          }
        }
      },
      "required": [
        "channels",
        "requirements"
      ]
    },
    "PythonRequirement": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "VoidFunction": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "description": "Provides documentation about the function, what it does, etc."
        },
        "input": {
          "type": "string",
          "description": "Refers to a protobuf message in model.proto that acts as the input to the function, e.g. 'DataFrame'."
        }
      },
      "required": [
        "description",
        "input"
      ]
    },
    "Function": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "description": "Provides documentation about the function, what it does, etc."
        },
        "input": {
          "type": "string",
          "description": "Refers to a protobuf message in model.proto that acts as the input to the function, e.g. 'DataFrame'."
        },
        "output": {
          "type": "string",
          "description": "Refers to a protobuf message in model.proto that acts as the output of the function, e.g. 'Prediction'."
        }
      },
      "required": [
        "description",
        "input",
        "output"
      ]
    }
  }
}

=== acumos/on-boarding/onboarding-common/src/test/resources/metadata.json
{
  "schema": "acumos.schema.model:0.4.0",
  "runtime": {
    "name": "python",
    "encoding": "protobuf",
    "version": "3.6.8",
    "dependencies": {
      "pip": {
        "indexes": [],
        "requirements": [
          {
            "name": "acumos",
            "version": "0.7.2"
          },
          {
            "name": "dill",
            "version": "0.2.7.1"
          }
        ]
      },
      "conda": {
        "channels": [],
        "requirements": []
      }
    }
  },
  "name": "example-model",
  "methods": {
    "add": {
      "input": "AddIn",
      "output": "AddOut",
      "description": "Adds two numbers"
    },
    "count": {
      "input": "CountIn",
      "output": "CountOut",
      "description": "Counts the occurrences of words in `strings`"
    }
  }
}
