=== acumos/on-boarding/onboarding-common/src/main/resources/model-schema-0.3.0.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "self": {
    "name": "acumos.schema.model",
    "version": "0.3.0"
  },
  "properties": {
    "schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "runtime": {
      "$ref": "#/definitions/Runtime"
    },
    "methods": {
      "type": "object",
      "properties": {
        "fit": {
          "$ref": "#/definitions/FitMethod"
        },
        "partial_fit": {
          "$ref": "#/definitions/FitMethod"
        },
        "transform": {
          "$ref": "#/definitions/TransformMethod"
        },
        "configure": {
          "$ref": "#/definitions/ConfigureMethod"
        },
        "classify": {
          "$ref": "#/definitions/ClassifyMethod"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "runtime",
    "schema"
  ],
  "definitions": {
    "Runtime": {
      "type": "object",
      "properties": {
        "name": {
          "enum": [
            "python",
            "r",
            "javaargus",
            "h2o",
            "javageneric",
            "javaspark"
          ]
        },
        "version": {
          "type": "string"
        },
        "encoding": {
          "enum": [
            "protobuf"
          ]
        },
        "dependencies": {
          "oneOf": [
            {
              "$ref": "#/definitions/PythonDependencies"
            },
            {
              "$ref": "#/definitions/RDependencies"
            },
            {
              "$ref": "#/definitions/H2ODependencies"
            }
          ]
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "H2ODependencies": {
      "type": "object",
      "properties": {
        "java": {
          "$ref": "#/definitions/JavaRequirements"
        }
      },
      "required": [
        "java"
      ]
    },
    "JavaRequirements": {
      "type": "object",
      "properties": {
        "indexes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "requirements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/H2ORequirement"
          }
        }
      },
      "required": [
        "indexes",
        "requirements"
      ]
    },
    "H2ORequirement": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "RDependencies": {
      "type": "object",
      "properties": {
        "packages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PackRequirements"
          }
        }
      },
      "required": [
        "packages"
      ]
    },
    "PackRequirements": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "PythonDependencies": {
      "type": "object",
      "properties": {
        "conda": {
          "$ref": "#/definitions/CondaRequirements"
        },
        "pip": {
          "$ref": "#/definitions/PipRequirements"
        }
      },
      "required": [
        "pip",
        "conda"
      ]
    },
    "PipRequirements": {
      "type": "object",
      "properties": {
        "indexes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "requirements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PythonRequirement"
          }
        }
      },
      "required": [
        "indexes",
        "requirements"
      ]
    },
    "CondaRequirements": {
      "type": "object",
      "properties": {
        "channels": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "requirements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PythonRequirement"
          }
        }
      },
      "required": [
        "channels",
        "requirements"
      ]
    },
    "PythonRequirement": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "FitMethod": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "input": {
          "type": "string"
        }
      },
      "required": [
        "description",
        "input"
      ]
    },
    "TransformMethod": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "input": {
          "type": "string"
        },
        "output": {
          "type": "string"
        }
      },
      "required": [
        "description",
        "input",
        "output"
      ]
    },
    "ConfigureMethod": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "input": {
          "type": "string"
        }
      },
      "required": [
        "description",
        "input"
      ]
    },
    "ClassifyMethod": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "input": {
          "type": "string"
        }
      },
      "required": [
        "description",
        "input"
      ]
    }
  }
}

=== acumos/on-boarding/onboarding-common/src/test/resources/modelDetails.json
{
 "schema": "acumos.schema.model:0.3.0",
 "name": "H2OModel",
 "runtime": {
   "encoding": "protobuf",
   "name": "h2o",
   "dependencies": {
     "java": {
       "indexes": [],
       "requirements": [
         {
           "name": "javac",
           "version": "1.8.0_131"
         },
         {
           "name": "java",
           "version": "1.8.0_131"
         },
         {
           "name": "protoc",
           "version": "3.4.0"
         }
       ]
     }
   },
   "version": "0.0.1"
 },
 "methods": {
   "transform": {
     "input": "DataFrame",
     "description": "Transforms a DataFrame to a Prediction",
     "output": "Prediction"
   }
 }
}
